on:
  release:
    types:
      - "created"

jobs:
  tags:
    runs-on: ubuntu-latest
    steps:
      # You have to check out your repo first.
      - uses: actions/checkout@v2
      - uses: fischerscode/tagger@v0.1
        with:
          # The prefix of the semantic tags.
          # Default: ''
          prefix: v
